"""Shared helpers for the behavioral/trace evaluation runners (stages 07, 08).

Why this module exists
----------------------
The old runners captured only pytest's quiet stdout, which truncates failure
reasons (``AssertionError: ...``). The aggregator then had to reconstruct test
status via regex and still lost per-test reasons. We now ask pytest to also
write a structured JSON report via the ``pytest-json-report`` plugin and embed
it into the per-agent entry. Nothing is lost, and the aggregator can display
the full ``longrepr`` for every failure.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any


PYTEST_REPORT_FILENAME = ".pytest_report.json"


def _load_report(report_path: Path) -> dict[str, Any] | None:
    if not report_path.exists():
        return None
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _normalize_tests(report: dict[str, Any]) -> list[dict[str, Any]]:
    """Flatten pytest-json-report tests into the shape the frontend consumes."""
    normalized = []
    for test in report.get("tests") or []:
        nodeid = test.get("nodeid") or ""
        short = nodeid.split("::", 1)[-1] if "::" in nodeid else nodeid
        outcome = test.get("outcome") or ""
        # longrepr is on the phase that failed/errored; call for actual test,
        # setup for fixture errors, teardown for cleanup errors.
        reason = ""
        for phase in ("call", "setup", "teardown"):
            info = test.get(phase) or {}
            lr = info.get("longrepr") or info.get("crash", {}).get("message")
            if lr:
                reason = lr if isinstance(lr, str) else str(lr)
                break
        normalized.append(
            {
                "name": short,
                "qualified_name": nodeid,
                "status": outcome,
                "passed": outcome == "passed",
                "reason": reason,
                "duration": test.get("duration"),
            }
        )
    return normalized


def run_pytest_for_agents(
    *,
    llm: str,
    agent_filter: str | None,
    test_filename: str,
    generated_dir: Path,
    bench_dir: Path,
    stage_label: str,
    stage_prefix: str,
    report_name_stem: str,
    experiments_results: Path,
) -> dict[str, Any]:
    """Run ``test_filename`` for every agent generated by ``llm`` and build a report.

    Parameters
    ----------
    llm
        LLM folder under ``generated_dir`` (e.g. ``"claude"``).
    agent_filter
        If provided, run only this agent folder (e.g. ``"001_list_issues_agent"``).
    test_filename
        Test file to copy from ``bench_dir/<agent>/`` into the agent folder
        before running pytest (e.g. ``"test_deepeval.py"`` or ``"test_trace.py"``).
    stage_label
        Human-readable stage used in the top-level ``"stage"`` field.
    stage_prefix
        Filename prefix for the written report (e.g. ``"07"`` or ``"08"``).
    report_name_stem
        Second segment of the filename (e.g. ``"test_deepeval"`` or
        ``"trace_eval"``).
    """

    if not generated_dir.exists():
        raise FileNotFoundError(f"Generated dir not found: {generated_dir}")
    if not bench_dir.exists():
        raise FileNotFoundError(f"Bench dir not found: {bench_dir}")

    model_folder = generated_dir / llm
    if not model_folder.exists():
        raise FileNotFoundError(f"LLM directory not found: {model_folder}")

    results: list[dict[str, Any]] = []

    for agent_folder in sorted(model_folder.iterdir()):
        if not agent_folder.is_dir():
            continue
        if agent_filter and agent_folder.name != agent_filter:
            continue

        entry: dict[str, Any] = {
            "model": llm,
            "agent_folder": agent_folder.name,
            "agent_file": "agent.py",
            "test_file": test_filename,
            "passed": None,
            "returncode": None,
            "stdout": None,
            "stderr": None,
            "error": None,
            "summary": None,
            "tests": [],
            "pytest_report": None,
        }

        agent_file = agent_folder / "agent.py"
        source_test = bench_dir / agent_folder.name / test_filename
        target_test = agent_folder / test_filename
        report_path = agent_folder / PYTEST_REPORT_FILENAME

        if not agent_file.exists():
            entry["error"] = "agent.py not found"
            results.append(entry)
            continue

        if not source_test.exists():
            entry["error"] = f"{test_filename} not found in specification directory"
            results.append(entry)
            continue

        try:
            shutil.copy2(source_test, target_test)

            print(f"Running {test_filename} for {agent_folder.name}...")

            result = subprocess.run(
                [
                    "python",
                    "-m",
                    "pytest",
                    test_filename,
                    "-v",
                    "--tb=long",
                    "-rN",  # no summary section (we have the json report)
                    "--json-report",
                    f"--json-report-file={PYTEST_REPORT_FILENAME}",
                    "--json-report-omit=keywords,warnings,streams,collectors",
                ],
                cwd=agent_folder,
                capture_output=True,
                text=True,
            )

            entry["passed"] = result.returncode == 0
            entry["returncode"] = result.returncode
            entry["stdout"] = result.stdout
            entry["stderr"] = result.stderr

            report = _load_report(report_path)
            if report is None:
                entry["error"] = (
                    "pytest-json-report did not produce a report; install "
                    "`pytest-json-report` to preserve test details."
                )
            else:
                entry["pytest_report"] = report
                entry["summary"] = report.get("summary")
                entry["tests"] = _normalize_tests(report)

        except Exception as exc:  # pragma: no cover - defensive
            entry["error"] = f"Error running tests: {exc}"
        finally:
            if target_test.exists():
                target_test.unlink()
            if report_path.exists():
                report_path.unlink()

        results.append(entry)

    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")

    final_report = {
        "run_id": run_id,
        "stage": stage_label,
        "model": llm,
        "test": test_filename,
        "agent_filter": agent_filter,
        "bench_dir": str(bench_dir),
        "generated_dir": str(generated_dir),
        "total_agents": len(results),
        "results": results,
    }

    report_path = (
        experiments_results
        / f"{stage_prefix}_{report_name_stem}_{llm}_{run_id}.json"
    )
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(final_report, indent=2, ensure_ascii=False, default=str),
        encoding="utf-8",
    )

    print(f"{stage_label} completed. Report saved to {report_path}")
    return final_report
